# Generated by Django 5.1 on 2024-08-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
